services:
  - type: web
    name: collaborative-drawing-backend
    runtime: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://doodlesphere-backend.onrender.com